name: Build and Deploy
on:
  pull_request:
    branches:
      - main
  push:
    paths: ["stories/**", "src/components/**", ".github/workflows/storybook.yml", "package.json"] # Trigger the action only when files change in the folders defined here
    branches: ["main"]
permissions:
  contents: write
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Install and Build 🔧
        run: | # Install npm packages and build the Storybook files
          npm install
          npm run build-storybook
      - name: Deploy to branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs-build # The folder the action should deploy.
          target-folder: . # The folder that we serve our Storybook files from
          clean: true
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
