name: Build and Deploy
on:
  pull_request:
    branches:
      - main
  push:
    paths: ["stories/**", "src/components/**", ".github/workflows/storybook.yml", "package.json", "webpack.entries.js"] # Trigger the action only when files change in the folders defined here
    branches: ["main"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
permissions:
  contents: write
  pages: write
  id-token: write
# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  build:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Set Yarn Version
        run: yarn set version berry
      - name: Install Dependencies
        run: yarn install
      - name: Lint with ESLint and stylelint
        run: yarn run lint:check
      - name: Build Storybook
        run: |
          yarn run build-storybook
          mv docs-build _site
      - name: Build bundle
        run: |
         yarn run build
         mv dist _site
      - name: Run tests with Jest 🧪
        run: |
          yarn test
      - name: Cache Jest cache
        uses: actions/cache@v2
        with:
          path: "**/node_modules/.cache/jest"
          key: jest-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            jest-${{ runner.os }}-
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: ./dist
